export default {
  ADD_TASK: 'ADD_TASK',
  EDIT_TASK: 'EDIT_TASK',
  REMOVE_TASK: 'REMOVE_TASK',
  COMPLETE_TASK: 'COMPLETE_TASK',
  TOGGLE_COMPLETED_ALL: 'TOGGLE_COMPLETED_ALL',
  REMOVE_COMPLETED: 'REMOVE_COMPLETED',
}